const apiUrl = (import.meta.env.VITE_API_URL ?? "").replace(/\/$/, ""); const base = `${apiUrl}/api`;
export type PerfilUsuario = "Administrador" | "RH" | "Gestor de Secretaria" | "Servidor";
export type Permissao = "visualizar" | "criar" | "editar" | "excluir";
export interface PrefeituraConfig { nome: string; cnpj: string; endereco: string; municipioUf: string; telefone: string; emailInstitucional: string; emailRh: string; responsavelRh: string; cargoResponsavel: string; logoUrl?: string; }
export interface RegrasRhConfig { alertaContratos: number; alertaQuinquenios: number; alertaFerias: number; prazoSolicitacaoFerias: number; percentualQuinquenio: number; anosAquisicaoQuinquenio: number; regrasFerias: string; regrasLicencas: string; }
export interface PreferenciasConfig { tema: "claro" | "escuro"; corPrincipal: string; formatoData: string; formatoMoeda: string; fusoHorario: string; }
export interface UsuarioConfig { id: string; nome: string; email: string; perfil: PerfilUsuario; bloqueado: boolean; ultimoAcesso?: string; permissoes: Record<string, Permissao[]>; }
export interface SessaoAtiva { id: string; dispositivo: string; localizacao?: string; ultimoAcesso: string; atual?: boolean; }
export interface SegurancaConfig { doisFatoresPreparado: boolean; ultimoAcesso?: string; sessoes: SessaoAtiva[]; }
export interface AuditoriaItem { id: string; usuario: string; acao: string; modulo: string; data: string; hora: string; registroAfetado: string; }
async function json<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(`${base}${url}`, { headers: { Accept: "application/json", ...(options?.body instanceof FormData ? {} : { "Content-Type": "application/json" }), ...options?.headers }, ...options }); if (!response.ok) throw new Error("Falha na comunicação com a API."); return response.json(); }
export const obterPrefeitura = () => json<PrefeituraConfig>("/configuracoes/prefeitura");
export const salvarPrefeitura = (dados: PrefeituraConfig, logo?: File) => { const form = new FormData(); form.append("dados", JSON.stringify(dados)); if (logo) form.append("logo", logo); return json<PrefeituraConfig>("/configuracoes/prefeitura", { method: "PUT", body: form }); };
export const obterRegras = () => json<RegrasRhConfig>("/configuracoes/regras-rh"); export const salvarRegras = (dados: RegrasRhConfig) => json<RegrasRhConfig>("/configuracoes/regras-rh", { method: "PUT", body: JSON.stringify(dados) });
export const obterPreferencias = () => json<PreferenciasConfig>("/configuracoes/preferencias"); export const salvarPreferencias = (dados: PreferenciasConfig) => json<PreferenciasConfig>("/configuracoes/preferencias", { method: "PUT", body: JSON.stringify(dados) });
export const listarUsuarios = () => json<UsuarioConfig[]>("/usuarios"); export const salvarUsuario = (dados: Omit<UsuarioConfig, "id" | "ultimoAcesso">, id?: string) => json<UsuarioConfig>(id ? `/usuarios/${id}` : "/usuarios", { method: id ? "PUT" : "POST", body: JSON.stringify(dados) }); export const excluirUsuario = (id: string) => json<void>(`/usuarios/${id}`, { method: "DELETE" }); export const alternarBloqueio = (id: string) => json<UsuarioConfig>(`/usuarios/${id}/bloqueio`, { method: "POST" }); export const redefinirSenha = (id: string) => json<void>(`/usuarios/${id}/redefinir-senha`, { method: "POST" });
export const obterSeguranca = () => json<SegurancaConfig>("/seguranca"); export const alternarDoisFatores = () => json<SegurancaConfig>("/seguranca/dois-fatores", { method: "POST" }); export const encerrarSessoes = () => json<void>("/seguranca/sessoes/encerrar-todas", { method: "POST" });
export const listarAuditoria = (filtros: Record<string, string>) => json<AuditoriaItem[]>(`/auditoria?${new URLSearchParams(filtros).toString()}`);
export async function baixarDados(path: string, nome: string) { const response = await fetch(`${base}${path}`, { method: "POST", headers: { Accept: "application/octet-stream" } }); if (!response.ok) throw new Error("Não foi possível gerar o arquivo."); const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = nome; link.click(); URL.revokeObjectURL(url); }
export const importarDados = (arquivo: File) => { const form = new FormData(); form.append("arquivo", arquivo); return json<void>("/dados/importar", { method: "POST", body: form }); };
