import { useEffect, useMemo, useState } from "react";
import type { Contrato, SituacaoContrato } from "../types";
import { listarContratos } from "../services/contratos";
import Icon from "../components/Icon";
import Status from "../components/Status";
type Props = { onNew: () => void };
const situacoes: SituacaoContrato[] = ["Ativo", "Aguardando assinatura", "Suspenso", "Encerrado", "Rescindido"];
export default function Contratos({ onNew }: Props) { const [items, setItems] = useState<Contrato[]>([]); const [query, setQuery] = useState(""); const [situacao, setSituacao] = useState("Todos"); const [loading, setLoading] = useState(true); const [erro, setErro] = useState(""); useEffect(() => { const c = new AbortController(); listarContratos(c.signal).then(setItems).catch(() => setErro("Não foi possível carregar os dados. Verifique a conexão com a API.")).finally(() => setLoading(false)); return () => c.abort(); }, []); const filtrados = useMemo(() => items.filter(i => (situacao === "Todos" || i.situacao === situacao) && `${i.servidor} ${i.matricula} ${i.numero} ${i.tipo}`.toLowerCase().includes(query.toLowerCase())), [items, query, situacao]); return <><div className="page-head"><div><h1>Contratos</h1><p>Controle de contratos temporários, comissionados e outros vínculos.</p></div><button className="btn primary" onClick={onNew}><Icon name="add" /> Novo Registro</button></div><div className="card table-card"><div className="filters"><div className="filter-search"><Icon name="search" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar..." /></div><select value={situacao} onChange={e => setSituacao(e.target.value)}><option>Todos</option>{situacoes.map(s => <option key={s}>{s}</option>)}</select><button className="btn outline"><Icon name="filter" /> Filtros</button></div><div className="table-scroll"><table className="table"><thead><tr><th>Servidor</th><th>Tipo de contrato</th><th>Início</th><th>Término</th><th>Situação</th></tr></thead><tbody>{loading ? <Mensagem>Carregando dados...</Mensagem> : erro ? <Mensagem>{erro}</Mensagem> : filtrados.length === 0 ? <Mensagem>Nenhum contrato encontrado.</Mensagem> : filtrados.map(i => <tr key={i.id}><td>{i.servidor}</td><td>{i.tipo}</td><td>{data(i.inicio)}</td><td>{data(i.termino)}</td><td><Status tone={tom(i.situacao)}>{i.situacao}</Status></td></tr>)}</tbody></table></div></div></>; }
function Mensagem({ children }: { children: string }) { return <tr><td colSpan={5} className="table-message">{children}</td></tr>; } function data(value: string) { return value ? value.split("-").reverse().join("/") : "—"; } function tom(s: SituacaoContrato) { return s === "Ativo" ? "green" : s === "Encerrado" || s === "Rescindido" ? "red" : s === "Suspenso" ? "yellow" : "blue"; }
