import { useEffect, useMemo, useState } from "react";
import type { Servidor, SituacaoSolicitacao, TipoSolicitacao } from "../types";
import { listarServidores } from "../services/servidores";
import { salvarSolicitacao } from "../services/solicitacoes";
import Icon from "../components/Icon";
type Props = { onBack: () => void };
const tipos: TipoSolicitacao[] = ["Férias", "Licença/Afastamento", "Declaração", "Atualização cadastral", "Documento", "Quinquênio", "Outro"]; const situacoes: SituacaoSolicitacao[] = ["Pendente", "Em análise", "Aprovada", "Rejeitada"];
export default function NovaSolicitacao({ onBack }: Props) { const [servidores, setServidores] = useState<Servidor[]>([]); const [servidorId, setServidorId] = useState(""); const [tipo, setTipo] = useState<TipoSolicitacao>("Férias"); const [data, setData] = useState(hoje()); const [descricao, setDescricao] = useState(""); const [situacao, setSituacao] = useState<SituacaoSolicitacao>("Pendente"); const [anexo, setAnexo] = useState<File>(); const [erro, setErro] = useState(""); const [salvando, setSalvando] = useState(false); useEffect(() => { const c = new AbortController(); listarServidores(c.signal).then(setServidores).catch(() => setErro("Não foi possível carregar os servidores. Verifique a conexão com a API.")); return () => c.abort(); }, []); const servidor = useMemo(() => servidores.find(s => s.id === servidorId), [servidores, servidorId]); async function salvar() { if (!servidor || !data || !descricao.trim()) return setErro("Preencha servidor, data e descrição da solicitação."); setSalvando(true); setErro(""); try { await salvarSolicitacao({ servidorId, servidor: servidor.nome, tipo, data, descricao: descricao.trim(), situacao }, anexo); onBack(); } catch { setErro("Não foi possível salvar a solicitação. Verifique a conexão com a API."); } finally { setSalvando(false); } } return <><div className="page-head"><div><h1>Nova Solicitação</h1><p>Registre uma solicitação do servidor.</p></div><button className="btn outline" onClick={onBack}><Icon name="arrow-left" /> Voltar</button></div><div className="card cadastro-servidor"><div className="form-grid ferias-form"><label className="full-col">Servidor<select value={servidorId} onChange={e => setServidorId(e.target.value)}><option value="">Selecione o servidor</option>{servidores.map(s => <option key={s.id} value={s.id}>{s.nome}</option>)}</select></label><label>Tipo de solicitação<select value={tipo} onChange={e => setTipo(e.target.value as TipoSolicitacao)}>{tipos.map(t => <option key={t}>{t}</option>)}</select></label><label>Data da solicitação<input type="date" value={data} onChange={e => setData(e.target.value)} required /></label><label>Situação<select value={situacao} onChange={e => setSituacao(e.target.value as SituacaoSolicitacao)}>{situacoes.map(s => <option key={s}>{s}</option>)}</select></label><label>Anexo opcional<input type="file" onChange={e => setAnexo(e.target.files?.[0])} /></label><label className="full-col">Descrição/observação<textarea value={descricao} onChange={e => setDescricao(e.target.value)} placeholder="Descreva a solicitação" required /></label></div>{erro && <p className="form-error">{erro}</p>}<div className="form-actions"><button className="btn outline" onClick={onBack}>Cancelar</button><button className="btn primary" disabled={salvando} onClick={salvar}>{salvando ? "Salvando..." : "Salvar Solicitação"}</button></div></div></>; }
function hoje() { return new Date().toISOString().slice(0, 10); }
