import { useEffect, useMemo, useState } from "react";
import type { Ferias, Servidor } from "../types";
import { listarFerias, salvarFerias } from "../services/ferias";
import { listarServidores } from "../services/servidores";
import Icon from "../components/Icon";

type Props = { onBack: () => void };
type Form = { servidorId: string; periodoAquisitivoInicio: string; periodoAquisitivoFim: string; diasDireito: number; inicio: string; fim: string; abonoPecuniario: boolean; antecipacaoDecimoTerceiro: boolean; observacoes: string };
const inicial: Form = { servidorId: "", periodoAquisitivoInicio: "", periodoAquisitivoFim: "", diasDireito: 30, inicio: "", fim: "", abonoPecuniario: false, antecipacaoDecimoTerceiro: false, observacoes: "" };
export default function NovaFerias({ onBack }: Props) {
  const [form, setForm] = useState<Form>(inicial); const [servidores, setServidores] = useState<Servidor[]>([]); const [registros, setRegistros] = useState<Ferias[]>([]); const [erro, setErro] = useState(""); const [salvando, setSalvando] = useState(false);
  useEffect(() => { const c = new AbortController(); Promise.all([listarServidores(c.signal), listarFerias(c.signal)]).then(([lista, ferias]) => { setServidores(lista); setRegistros(ferias); }).catch(() => setErro("Não foi possível carregar os dados necessários. Verifique a conexão com a API.")); return () => c.abort(); }, []);
  const servidor = useMemo(() => servidores.find(s => s.id === form.servidorId), [servidores, form.servidorId]); const dias = diasEntre(form.inicio, form.fim);
  const atualizar = <K extends keyof Form>(campo: K, valor: Form[K]) => setForm(atual => ({ ...atual, [campo]: valor }));
  async function salvar() { if (!servidor) return setErro("Selecione um servidor cadastrado."); const mensagem = validar(form, dias, registros); if (mensagem) return setErro(mensagem); setSalvando(true); setErro(""); try { await salvarFerias({ ...form, servidor: servidor.nome, matricula: servidor.matricula, cpf: servidor.cpf ?? "", cargo: servidor.cargo, secretaria: servidor.secretaria, dias, situacao: "Pendente" }); onBack(); } catch { setErro("Não foi possível salvar as férias. Verifique a conexão com a API."); } finally { setSalvando(false); } }
  return <><div className="page-head"><div><h1>Novo registro de férias</h1><p>Informe os dados do período de férias do servidor.</p></div><button className="btn outline" onClick={onBack}><Icon name="arrow-left" /> Voltar</button></div><div className="card cadastro-servidor"><div className="form-grid ferias-form"><label className="full-col">Servidor<select value={form.servidorId} onChange={e => atualizar("servidorId", e.target.value)}><option value="">Selecione o servidor</option>{servidores.map(s => <option key={s.id} value={s.id}>{s.nome}</option>)}</select></label><Info label="Matrícula" value={servidor?.matricula} /><Info label="CPF" value={servidor?.cpf} /><Info label="Cargo" value={servidor?.cargo} /><Info label="Secretaria" value={servidor?.secretaria} /><Campo label="Início do período aquisitivo" type="date" value={form.periodoAquisitivoInicio} onChange={v => atualizar("periodoAquisitivoInicio", v)} /><Campo label="Fim do período aquisitivo" type="date" value={form.periodoAquisitivoFim} onChange={v => atualizar("periodoAquisitivoFim", v)} /><Campo label="Dias de direito" type="number" value={String(form.diasDireito)} onChange={v => atualizar("diasDireito", Number(v))} /><Campo label="Início das férias" type="date" value={form.inicio} onChange={v => atualizar("inicio", v)} /><Campo label="Fim das férias" type="date" value={form.fim} onChange={v => atualizar("fim", v)} /><Info label="Dias de férias" value={dias ? String(dias) : "—"} /><Booleano label="Abono pecuniário" value={form.abonoPecuniario} onChange={v => atualizar("abonoPecuniario", v)} /><Booleano label="Antecipação do 13º" value={form.antecipacaoDecimoTerceiro} onChange={v => atualizar("antecipacaoDecimoTerceiro", v)} /><label className="full-col">Observações<textarea value={form.observacoes} onChange={e => atualizar("observacoes", e.target.value)} placeholder="Observações adicionais" /></label></div>{erro && <p className="form-error">{erro}</p>}<div className="form-actions"><button className="btn outline" onClick={onBack}>Cancelar</button><button className="btn primary" onClick={salvar} disabled={salvando}>{salvando ? "Salvando..." : "Salvar registro"}</button></div></div></>;
}
function Info({ label, value }: { label: string; value?: string }) { return <label>{label}<input value={value ?? "—"} readOnly /></label>; }
function Campo({ label, type, value, onChange }: { label: string; type: string; value: string; onChange: (value: string) => void }) { return <label>{label}<input type={type} value={value} onChange={e => onChange(e.target.value)} required /></label>; }
function Booleano({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label>{label}<select value={value ? "sim" : "nao"} onChange={e => onChange(e.target.value === "sim")}><option value="nao">Não</option><option value="sim">Sim</option></select></label>; }
function diasEntre(inicio: string, fim: string) { if (!inicio || !fim) return 0; const a = Date.parse(`${inicio}T00:00:00Z`); const b = Date.parse(`${fim}T00:00:00Z`); return b < a ? 0 : Math.floor((b - a) / 86400000) + 1; }
function validar(form: Form, dias: number, registros: Ferias[]) { if (!form.periodoAquisitivoInicio || !form.periodoAquisitivoFim || !form.inicio || !form.fim) return "Preencha todas as datas obrigatórias."; if (form.periodoAquisitivoFim < form.periodoAquisitivoInicio) return "O fim do período aquisitivo deve ser posterior ao início."; if (form.fim < form.inicio) return "O fim das férias deve ser posterior ao início."; if (dias > form.diasDireito) return "A quantidade de dias de férias não pode ser maior que os dias de direito."; return registros.some(r => r.servidorId === form.servidorId && r.situacao !== "Cancelada" && form.inicio <= r.fim && form.fim >= r.inicio) ? "Já existe um período de férias sobreposto para este servidor." : ""; }
