import { useEffect, useMemo, useState } from "react";
import type { Quinquenio, SituacaoQuinquenio } from "../types";
import { listarQuinquenios } from "../services/quinquenios";
import Icon from "../components/Icon";
import Status from "../components/Status";
type Props = { onNew: () => void };
const situacoes: SituacaoQuinquenio[] = ["Em análise", "Aguardando concessão", "Concedido", "Implantado", "Suspenso", "Cancelado"];
export default function Quinquenios({ onNew }: Props) { const [items, setItems] = useState<Quinquenio[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [erro, setErro] = useState(""); useEffect(() => { const c = new AbortController(); listarQuinquenios(c.signal).then(setItems).catch(() => setErro("Não foi possível carregar os dados. Verifique a conexão com a API.")).finally(() => setLoading(false)); return () => c.abort(); }, []); const filtrados = useMemo(() => items.filter(i => `${i.servidor} ${i.matricula} ${i.numero} ${i.situacao}`.toLowerCase().includes(query.toLowerCase())), [items, query]); return <><div className="page-head"><div><h1>Quinquênios</h1><p>Controle dos adicionais por tempo de serviço.</p></div><button className="btn primary" onClick={onNew}><Icon name="add" /> Novo Registro</button></div><div className="card table-card"><div className="filters"><div className="filter-search"><Icon name="search" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar..." /></div><select><option>Todos</option>{situacoes.map(s => <option key={s}>{s}</option>)}</select><button className="btn outline"><Icon name="filter" /> Filtros</button></div><div className="table-scroll"><table className="table"><thead><tr><th>Servidor</th><th>Quinquênio</th><th>Data de aquisição</th><th>Percentual</th><th>Situação</th></tr></thead><tbody>{loading ? <Mensagem>Carregando dados...</Mensagem> : erro ? <Mensagem>{erro}</Mensagem> : filtrados.length === 0 ? <Mensagem>Nenhum quinquênio encontrado.</Mensagem> : filtrados.map(i => <tr key={i.id}><td>{i.servidor}</td><td>{i.numero}º ({i.numero * 5} anos)</td><td>{data(i.dataAquisicao)}</td><td>{i.percentualAdicional}%</td><td><Status tone={tom(i.situacao)}>{i.situacao}</Status></td></tr>)}</tbody></table></div></div></>; }
function Mensagem({ children }: { children: string }) { return <tr><td colSpan={5} className="table-message">{children}</td></tr>; } function data(value: string) { return value ? value.split("-").reverse().join("/") : "—"; } function tom(s: SituacaoQuinquenio) { return s === "Concedido" || s === "Implantado" ? "green" : s === "Suspenso" || s === "Cancelado" ? "red" : s === "Aguardando concessão" ? "yellow" : "blue"; }
