import { useEffect, useState } from "react";
import { BrowserRouter, Navigate, Outlet, Route, Routes, useNavigate, useParams } from "react-router-dom";
import type { Servidor } from "./types";
import Sidebar from "./components/Sidebar"; import Header from "./components/Header";
import Dashboard from "./pages/Dashboard"; import Servidores from "./pages/Servidores"; import NovoServidor from "./pages/NovoServidor"; import PerfilServidor from "./pages/PerfilServidor"; import Ferias from "./pages/Ferias"; import NovaFerias from "./pages/NovaFerias"; import Licencas from "./pages/Licencas"; import NovaLicenca from "./pages/NovaLicenca"; import Contratos from "./pages/Contratos"; import NovoContrato from "./pages/NovoContrato"; import Frequencia from "./pages/Frequencia"; import Quinquenios from "./pages/Quinquenios"; import NovoQuinquenio from "./pages/NovoQuinquenio"; import Solicitacoes from "./pages/Solicitacoes"; import NovaSolicitacao from "./pages/NovaSolicitacao"; import Documentos from "./pages/Documentos"; import NovoDocumento from "./pages/NovoDocumento"; import Relatorios from "./pages/Relatorios"; import ConfigurarRelatorio from "./pages/ConfigurarRelatorio"; import Configuracoes from "./pages/Configuracoes";
import { listarServidores } from "./services/servidores";
import Requerimentos from "./pages/Requerimentos";
import NovoRequerimento from "./pages/NovoRequerimento";
import DetalheRequerimento from "./pages/DetalheRequerimento";
import Login from "./pages/Login";

export default function App() {
  const [logged, setLogged] = useState(false);
  return <BrowserRouter><Routes>
    <Route path="/login" element={<Login onLogin={() => setLogged(true)} logged={logged} />} />
    <Route element={<Protected logged={logged} />}>
      <Route path="/dashboard" element={<DashboardRoute />} />
      <Route path="/servidores" element={<ServidoresRoute />} /><Route path="/servidores/novo" element={<NovoServidorRoute />} /><Route path="/servidores/:id" element={<PerfilRoute />} />
      <Route path="/ferias" element={<FeriasRoute />} /><Route path="/ferias/novo" element={<NovaFeriasRoute />} /><Route path="/licencas" element={<LicencasRoute />} /><Route path="/licencas/novo" element={<NovaLicencaRoute />} />
      <Route path="/contratos" element={<ContratosRoute />} /><Route path="/contratos/novo" element={<NovoContratoRoute />} /><Route path="/frequencia" element={<Frequencia />} />
      <Route path="/quinquenios" element={<QuinqueniosRoute />} /><Route path="/quinquenios/novo" element={<NovoQuinquenioRoute />} /><Route path="/solicitacoes" element={<SolicitacoesRoute />} /><Route path="/solicitacoes/nova" element={<NovaSolicitacaoRoute />} />
      <Route path="/documentos" element={<DocumentosRoute />} /><Route path="/documentos/novo" element={<NovoDocumentoRoute />} />
      <Route path="/requerimentos" element={<RequerimentosRoute />} /><Route path="/requerimentos/novo" element={<NovoRequerimentoRoute />} /><Route path="/requerimentos/:id/editar" element={<EditarRequerimentoRoute />} /><Route path="/requerimentos/:id" element={<DetalheRequerimentoRoute />} />
      <Route path="/relatorios" element={<RelatoriosRoute />} />
      {(["servidores", "ferias", "licencas", "quinquenios", "contratos", "frequencia", "admissoes", "desligamentos"] as const).map(tipo => <Route key={tipo} path={`/relatorios/${tipo}`} element={<RelatorioRoute tipo={tipo} />} />)}
      <Route path="/configuracoes" element={<Configuracoes />} /><Route path="/configuracoes/prefeitura" element={<Configuracoes initialTab="prefeitura" />} /><Route path="/configuracoes/regras" element={<Configuracoes initialTab="regras" />} /><Route path="/configuracoes/usuarios" element={<Configuracoes initialTab="usuarios" />} /><Route path="/configuracoes/seguranca" element={<Configuracoes initialTab="seguranca" />} /><Route path="/configuracoes/auditoria" element={<Configuracoes initialTab="auditoria" />} /><Route path="/configuracoes/backup" element={<Configuracoes initialTab="dados" />} /><Route path="/configuracoes/aparencia" element={<Configuracoes initialTab="aparencia" />} />
    </Route><Route path="/" element={<Navigate to="/dashboard" replace />} /><Route path="*" element={<Navigate to="/dashboard" replace />} />
  </Routes></BrowserRouter>;
}
function Protected({ logged }: { logged: boolean }) { return logged ? <div className="app"><Sidebar /><main className="main"><Header /><section className="content"><Outlet /></section></main></div> : <Navigate to="/login" replace />; }
function DashboardRoute() { const nav = useNavigate(); return <Dashboard navigate={screen => nav(`/${screen}`)} />; } function ServidoresRoute() { const nav = useNavigate(); return <Servidores onProfile={s => nav(`/servidores/${s.id}`)} onNew={() => nav("/servidores/novo")} />; } function NovoServidorRoute() { const nav = useNavigate(); return <NovoServidor onBack={() => nav("/servidores")} />; } function FeriasRoute() { const nav = useNavigate(); return <Ferias onNew={() => nav("/ferias/novo")} />; } function NovaFeriasRoute() { const nav = useNavigate(); return <NovaFerias onBack={() => nav("/ferias")} />; } function LicencasRoute() { const nav = useNavigate(); return <Licencas onNew={() => nav("/licencas/novo")} />; } function NovaLicencaRoute() { const nav = useNavigate(); return <NovaLicenca onBack={() => nav("/licencas")} />; } function ContratosRoute() { const nav = useNavigate(); return <Contratos onNew={() => nav("/contratos/novo")} />; } function NovoContratoRoute() { const nav = useNavigate(); return <NovoContrato onBack={() => nav("/contratos")} />; } function QuinqueniosRoute() { const nav = useNavigate(); return <Quinquenios onNew={() => nav("/quinquenios/novo")} />; } function NovoQuinquenioRoute() { const nav = useNavigate(); return <NovoQuinquenio onBack={() => nav("/quinquenios")} />; } function SolicitacoesRoute() { const nav = useNavigate(); return <Solicitacoes onNew={() => nav("/solicitacoes/nova")} />; } function NovaSolicitacaoRoute() { const nav = useNavigate(); return <NovaSolicitacao onBack={() => nav("/solicitacoes")} />; } function DocumentosRoute() { const nav = useNavigate(); return <Documentos onNew={() => nav("/documentos/novo")} />; } function NovoDocumentoRoute() { const nav = useNavigate(); return <NovoDocumento onBack={() => nav("/documentos")} />; } function RelatoriosRoute() { const nav = useNavigate(); return <Relatorios onConfigurar={tipo => nav(`/relatorios/${tipo}`)} />; }
function RequerimentosRoute() { const nav = useNavigate(); return <Requerimentos onNew={() => nav("/requerimentos/novo")} onView={id => nav(`/requerimentos/${id}`)} onEdit={id => nav(`/requerimentos/${id}/editar`)} />; }
function NovoRequerimentoRoute() { const nav = useNavigate(); return <NovoRequerimento onBack={() => nav("/requerimentos")} onSaved={id => nav(`/requerimentos/${id}`)} />; }
function EditarRequerimentoRoute() { const nav = useNavigate(); const { id } = useParams(); return id ? <NovoRequerimento id={id} onBack={() => nav(`/requerimentos/${id}`)} onSaved={salvo => nav(`/requerimentos/${salvo}`)} /> : <Navigate to="/requerimentos" replace />; }
function DetalheRequerimentoRoute() { const nav = useNavigate(); const { id } = useParams(); return id ? <DetalheRequerimento id={id} onBack={() => nav("/requerimentos")} onEdit={() => nav(`/requerimentos/${id}/editar`)} /> : <Navigate to="/requerimentos" replace />; }
function RelatorioRoute({ tipo }: { tipo: Parameters<typeof ConfigurarRelatorio>[0]["tipo"] }) { const nav = useNavigate(); return <ConfigurarRelatorio tipo={tipo} onBack={() => nav("/relatorios")} />; }
function PerfilRoute() { const { id } = useParams(); const nav = useNavigate(); const [servidor, setServidor] = useState<Servidor | null>(null); const [erro, setErro] = useState(""); useEffect(() => { const c = new AbortController(); listarServidores(c.signal).then(lista => setServidor(lista.find(s => s.id === id) ?? null)).catch(() => setErro("Não foi possível carregar o perfil do servidor.")); return () => c.abort(); }, [id]); if (erro) return <p className="form-error">{erro}</p>; if (!servidor) return <p className="table-message">Carregando perfil do servidor...</p>; return <PerfilServidor servidor={servidor} onQuinquenios={() => nav("/quinquenios")} />; }
